### ISSUE TITLE
Error when starting CTGP-7 (I have a save file in mariokart 7...)

### ISSUE THREAD

**Issue by tntboom5656** [CTGP-7/ctgp-7.github.io#4]
I have a save file in mariokart 7. Despite that, it's asking me for a save file. Here's an image.
![unnamed (2)](https://user-images.githubusercontent.com/77867291/110037273-09e79080-7cf3-11eb-8c5c-8d320e5dddbc.jpg)

**Comment by mariohackandglitch** [comment]
Hello!
This bug has just been fixed, please update to v1.1.26.

**Comment by tntboom5656** [comment]
Thanks!
