### ISSUE TITLE
CTGP-7 does not recognize mikewii's latest plugin loader version as latest, gives prompt to update

### ISSUE THREAD

**Issue by Mewthree3** [CTGP-7/ctgp-7.github.io#5]
[This ](https://github.com/mikewii/Luma3DS-plugin/releases/tag/r1.0.10)is the latest verison.([https://github.com/mikewii/Luma3DS-plugin/releases/tag/r1.0.10](url))
Please update this ASAP, I want to use CTGP-7 and keep up to date as well.
Thank you

**Comment by mariohackandglitch** [comment]
Works as intended, only the main plugin loader version is compatible with CTGP7. Other forks are not supported.

The solution here is to use the luma chainloader to select which .firm file you want to use.
